version: '3.4'

services:

  mockoon:
    image: mockoon/cli
    command: -p 8180 -d /config/users-api.json
    networks:
      - mockoon
    ports:
      - "8180:8180"
    volumes:
      - ./mockoon:/config

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "blue-elephant" #Postgres's logo is an elephant :P
    ports:
      - "65432:5432" #Different port to not conflict with any possible real/default Postgres installation

networks:
  mockoon:
    driver: bridge
